/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HelloWorld } from "./HelloWorld";
export * as factories from "../test/factories";
export { HelloWorld__factory } from "../test/factories/HelloWorld__factory";
